"""
Django settings for restaurantBE project.
Generated by 'django-admin startproject' using Django 3.2.14.
For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "drf_yasg",
    "restaurantBE.accounts",
    "restaurantBE.upload",
    "restaurantBE.tables",
    "restaurantBE.guests",
    "restaurantBE.dishes",
    "restaurantBE.categories",
    "restaurantBE.orders",
    "restaurantBE.analist",
    "restaurantBE.chatbot",
]
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # Middleware đa ngôn ngữ
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
ROOT_URLCONF = "restaurantBE.urls"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
WSGI_APPLICATION = "restaurantBE.wsgi.application"
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
LANGUAGE_CODE = "vi"
TIME_ZONE = "Asia/Ho_Chi_Minh"
USE_I18N = True
USE_L10N = True
USE_TZ = True
LANGUAGES = [("vi", "Tiếng Việt"), ("en", "English")]
LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "/static/"
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# Rest framework option
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "restaurantBE.authentication.AccountJWTAuthentication",
        "restaurantBE.authentication.GuestJWTAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 10,
    "EXCEPTION_HANDLER": "restaurantBE.utils.exceptions.CustomExceptionHandler",
}
# auth config
AUTH_USER_MODEL = "accounts.Account"
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
# JWT config
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=15),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": "t3llqPQAgIfXbfFwlChpabcdujYOFsjXz2sI",
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
}
# Docs
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {"type": "apiKey", "name": "Authorization", "in": "header"}
    }
}
# VNPAY
VNPAY_TMN_CODE = os.getenv("VNPAY_TMN_CODE")
VNPAY_HASH_SECRET = os.getenv("VNPAY_HASH_SECRET")
VNPAY_PAYMENT_URL = os.getenv("VNPAY_PAYMENT_URL")
VNPAY_RETURN_URL = os.getenv("VNPAY_RETURN_URL")
VNPAY_ORDER_TYPE = os.getenv("VNPAY_ORDER_TYPE")
CLIENT_URL = os.getenv("CLIENT_URL", "http://localhost:3000")
# Redis (used by Socket.IO AsyncRedisManager for cross-process emit)
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "TIMEOUT": int(os.getenv("DJANGO_CACHE_TIMEOUT_DEFAULT", 3600)),
    }
}
# Translation
LOCALIZED_FIELD_LANGUAGES = tuple(code for code, _ in LANGUAGES)
GOOGLE_TRANSLATION_ENABLED = os.getenv(
    "GOOGLE_TRANSLATION_ENABLED", "false"
).lower() in {
    "1",
    "true",
    "yes",
    "on",
}
GOOGLE_TRANSLATION_PROJECT_ID = os.getenv("GOOGLE_TRANSLATION_PROJECT_ID")
GOOGLE_TRANSLATION_LOCATION = os.getenv("GOOGLE_TRANSLATION_LOCATION", "global")
# Chatbot embedding
CHATBOT_EMBEDDING_PROVIDER = os.getenv("CHATBOT_EMBEDDING_PROVIDER", "local")
CHATBOT_EMBEDDING_MODEL = os.getenv("CHATBOT_EMBEDDING_MODEL")
if not CHATBOT_EMBEDDING_MODEL:
    if CHATBOT_EMBEDDING_PROVIDER == "gemini":
        CHATBOT_EMBEDDING_MODEL = "gemini-embedding-001"
    else:
        CHATBOT_EMBEDDING_MODEL = "intfloat/multilingual-e5-small"

CHATBOT_EMBEDDING_DEVICE = os.getenv("CHATBOT_EMBEDDING_DEVICE", "cpu")
CHATBOT_EMBEDDING_BATCH_SIZE = int(os.getenv("CHATBOT_EMBEDDING_BATCH_SIZE", "32"))
CHATBOT_EMBEDDING_NORMALIZE = os.getenv("CHATBOT_EMBEDDING_NORMALIZE", "true").lower() in {"1", "true", "yes", "on"}
CHATBOT_EMBEDDING_BASE_URL = os.getenv("CHATBOT_EMBEDDING_BASE_URL")

# Resolve API key prioritizing CHATBOT_EMBEDDING_API_KEY, then EMBEDDING_API_KEY
CHATBOT_EMBEDDING_API_KEY = (
    os.getenv("CHATBOT_EMBEDDING_API_KEY")
    or os.getenv("EMBEDDING_API_KEY")
)

# Output dimension size and timeout settings
CHATBOT_EMBEDDING_DIMENSIONS = os.getenv("CHATBOT_EMBEDDING_DIMENSIONS")
if CHATBOT_EMBEDDING_DIMENSIONS:
    CHATBOT_EMBEDDING_DIMENSIONS = int(CHATBOT_EMBEDDING_DIMENSIONS)
else:
    CHATBOT_EMBEDDING_DIMENSIONS = 768

CHATBOT_EMBEDDING_TIMEOUT_SECONDS = int(os.getenv("CHATBOT_EMBEDDING_TIMEOUT_SECONDS", "30"))
NVIDIA_API_KEY = os.getenv("NVIDIA_API_KEY")
# Chatbot LLM provider: gemini | groq
CHATBOT_LLM_PROVIDER = os.getenv("CHATBOT_LLM_PROVIDER", "gemini").lower()
CHATBOT_LLM_MODEL = os.getenv("CHATBOT_LLM_MODEL", "")
CHATBOT_LLM_TEMPERATURE = float(os.getenv("CHATBOT_LLM_TEMPERATURE", "0.2"))
CHATBOT_LLM_MAX_TOKENS = int(os.getenv("CHATBOT_LLM_MAX_TOKENS", "300"))
CHATBOT_LLM_REASONING_ENABLED = os.getenv(
    "CHATBOT_LLM_REASONING_ENABLED", "false"
).lower() in {"1", "true", "yes", "on"}
# API keys for LLM providers
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
CHATBOT_LLM_BASE_URL = os.getenv("CHATBOT_LLM_BASE_URL", "")
# Local Chroma vector DB
CHATBOT_CHROMA_DIR = os.getenv("CHATBOT_CHROMA_DIR")
CHATBOT_CHROMA_COLLECTION = os.getenv("CHATBOT_CHROMA_COLLECTION", "restaurant_chatbot")