# Generated by Django 3.2.14 on 2026-04-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_account_owner'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='chatbot_con_account_91f31d_idx',
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['account', 'created_at'], name='chatbot_con_account_3206be_idx'),
        ),
    ]
