# Generated by Django 3.2.14 on 2026-02-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'available'), ('Reserved ', 'reserved'), ('HIDDEN', 'hidden')], default='AVAILABLE', max_length=20)),
                ('token', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Table',
            },
        ),
    ]
