# Generated by Django 3.2.14 on 2026-02-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'available'), ('RESERVED', 'reserved'), ('HIDDEN', 'hidden')], default='AVAILABLE', max_length=20),
        ),
    ]
