# Generated by Django 3.2.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0003_alter_table_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="table",
            index=models.Index(fields=["status"], name="idx_table_status"),
        ),
    ]
