# Generated by Django 3.2.14 on 2026-02-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sortOrder',
        ),
    ]
