# Generated by Django 3.2.14 on 2026-02-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20260226_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.JSONField(max_length=255),
        ),
    ]
