# Generated by Django 3.2.14 on 2026-03-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
