# Generated by Django 3.2.14 on 2026-03-03 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guests', '0003_auto_20260226_1727'),
        ('tables', '0002_alter_table_status'),
        ('dishes', '0003_auto_20260303_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('PREPARING', 'preparing'), ('SERVED', 'served'), ('CANCELLED', 'cancelled'), ('COMPLETED', 'completed')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'cash'), ('QR_CODE', 'qr_code')], default='CASH', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guests.guest')),
                ('order_handler_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.table')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('item_status', models.CharField(choices=[('ORDERED', 'ordered'), ('COOKING', 'cooking'), ('SERVED', 'served'), ('CANCELLED', 'cancelled')], default='ORDERED', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish_snapshot_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dishes.dishsnapshot')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
