# Generated by Django 3.2.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_order_handler_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["created_at"], name="idx_order_created_at"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"],
                name="idx_order_status_created_at",
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order_id"], name="idx_order_item_order_id"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["dish_snapshot_id"], name="idx_order_item_snapshot_id"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["created_at"], name="idx_order_item_created_at"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["item_status"], name="idx_order_item_status"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["item_status", "order_id"],
                name="idx_order_item_status_order",
            ),
        ),
    ]
