# Generated by Django 3.2.14 on 2026-02-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('EMPLOYEE', 'employee')], default='EMPLOYEE', max_length=20),
        ),
    ]
