# Generated by Django 3.2.14 on 2026-02-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('EMPLOYEE', 'employee'), ('GUEST', 'guest')], default='EMPLOYEE', max_length=20),
        ),
    ]
