# Generated by Django 3.2.14 on 2026-02-10 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('refeshToken', models.CharField(max_length=255)),
                ('refreshTokenExpiryAt', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('tableNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table')),
            ],
            options={
                'db_table': 'Guest',
            },
        ),
    ]
