# Generated by Django 3.2.14 on 2026-02-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='refeshToken',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='refreshTokenExpiryAt',
        ),
        migrations.AddField(
            model_name='guest',
            name='refreshToken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='refreshTokenExpiresAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
