# Generated by Django 3.2.14 on 2026-02-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20260211_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='refreshToken',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='refreshTokenExpiresAt',
        ),
    ]
