# Generated by Django 3.2.14 on 2026-02-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AVAILABLE', 'available'), ('UNAVAILABLE', 'unavailable'), ('HIDDEN', 'hidden')], default='AVAILABLE', max_length=20)),
                ('category_id', models.IntegerField(null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Dish',
            },
        ),
    ]
