# Generated by manual migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0001_initial"),
    ]

    operations = [
        # Delete old table
        migrations.DeleteModel(
            name="Dish",
        ),
        # Create new table with correct structure
        migrations.CreateModel(
            name="Dish",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.JSONField()),
                ("price", models.IntegerField()),
                ("description", models.JSONField()),
                ("image", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "available"),
                            ("UNAVAILABLE", "unavailable"),
                            ("HIDDEN", "hidden"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("category_id", models.IntegerField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Dish",
            },
        ),
    ]
