# Generated by Django 3.2.14 on 2026-03-03 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20260226_1727'),
        ('dishes', '0002_auto_dish_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DishSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField()),
                ('price', models.IntegerField()),
                ('description', models.JSONField()),
                ('image', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AVAILABLE', 'available'), ('UNAVAILABLE', 'unavailable'), ('HIDDEN', 'hidden')], default='AVAILABLE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.dish')),
            ],
            options={
                'db_table': 'DishSnapshot',
            },
        ),
    ]
