# Generated by Django 3.2.14 on 2026-03-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_auto_20260303_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishsnapshot',
            name='status',
        ),
        migrations.AlterModelTable(
            name='dish',
            table='dish',
        ),
        migrations.AlterModelTable(
            name='dishsnapshot',
            table='dish_snapshot',
        ),
    ]
