# Generated by Django 3.2.14 on 2026-03-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_auto_20260303_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dishsnapshot',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
