# Generated by Django 3.2.14 on 2026-03-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_fix_dish_category_column'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['status'], name='idx_dish_status'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['category_id'], name='idx_dish_category'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['created_at'], name='idx_dish_created_at'),
        ),
        migrations.AddIndex(
            model_name='dishsnapshot',
            index=models.Index(fields=['dish_id'], name='idx_ds_dish_id'),
        ),
        migrations.AddIndex(
            model_name='dishsnapshot',
            index=models.Index(fields=['created_at'], name='idx_ds_created_at'),
        ),
        migrations.AddIndex(
            model_name='dishsnapshot',
            index=models.Index(fields=['updated_at'], name='idx_ds_updated_at'),
        ),
    ]
