# Generated by Django 3.2.14 on 2026-04-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_auto_20260401_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dishsnapshot',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
